import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Explicit, not autogenerated: five pages in a deliberate reading order.
const sidebars: SidebarsConfig = {
  docsSidebar: ['intro', 'configuration', 'dashboard', 'example', 'privacy'],
};

export default sidebars;
